languageCode = "en-us"
baseurl = "https://harryho.github.io"
title = "Hello World"
theme = "bootie-docs"
uglyurls = false
copyright = "Copyright (c) 2015, harryho; All rights reserved."
enableRobotsTXT = true
disqusShortname = "harryho"

[params]
  description = "Collect simple & smart ideas. Refine practical & reusable solutions. It is a note site, not a blog site"
  withSitePosts = false
  searchDomain = "harryho.github.io"
  noCategoryLink = true
  repositoryUrl = "https://github.com/harryho/harryho.github.io.git"
  # highlightStyle = "railscasts"
  highlightStyle = "github"

[[params.mainMenu]]
  name = "Info"
  link = "info/"

[[params.mainMenu]]
  name = "Code"
  link = "code/" 

[[menu.code]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/java/"
[[menu.code]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/java/"


[[params.mainMenu]]
  name = "Dev"
  link = "dev/"  

[[params.mainMenu]]
  name = "OS"
  link = "os/"  

#[[params.mainMenu]]
#   name = "Cloud"
#   link = "cloud/" 

[[params.mainMenu]]
  name = "Project"
  link = "project/"

#[[params.mainMenu]]
#  name = "Index"
#  link = "index/"