languageCode = "en-us"
baseurl = "https://harryho.github.io"
title = "Welcome to Hello World"
theme = "bootie-docs"
uglyurls = false
copyright = "Copyright (c) 2015, harryho; All rights reserved."
enableRobotsTXT = true
disqusShortname = "harryhounique"

[params]
  description = "Blog site for simple & reusable techies"
  withSitePosts = false
  searchDomain = "harryho.github.io"
  noCategoryLink = true
  repositoryUrl = "https://github.com/harryho/harryho.github.io.git"
  highlightStyle = "railscasts"

[[params.mainMenu]]
  name = "Blog"
  link = "blog/"

[[params.mainMenu]]
  name = "Project"
  link = "project/"

[[params.mainMenu]]
  name = "Index"
  link = "index/"